version: '3'

services:
  subsys_admin:
    build: 
      context: ../backend-admin
    environment: 
      ENV: "development"
    ports: 
      - 9911:8000
    volumes: 
      - ../backend-admin/app:/home/admin/app
    networks:
      back-end:
        ipv4_address: ${BACKEND_ADMIN_IP}

  subsys_researcher:
    build: 
      context: ../backend-researcher
    environment: 
      ENV: "development"
    ports: 
      - 9912:8000
    volumes: 
      - ../backend-researcher/app:/home/researcher/app
    networks:
      back-end:
        ipv4_address: ${BACKEND_RESEARCHER_IP}

  subsys_tracer:
    build: 
      context: ../backend-tracer
    environment: 
      ENV: "development"
    ports: 
      - 9913:8000
    volumes: 
      - ../backend-tracer/app:/home/tracer/app
    networks:
      back-end:
        ipv4_address: ${BACKEND_TRACER_IP}
      
  db_main:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_MAIN_PSWD}
    ports: # host:container 
      - ${MYSQL_MAIN_PORT}:3306
    volumes:
      - ${MYSQL_MAIN_DATA}:/var/lib/mysql
    networks:
      database:
        ipv4_address: ${MYSQL_MAIN_IP}

  db_sub:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_SUB_PSWD}
    ports: # host:container
      - ${MYSQL_SUB_PORT}:3306
    volumes:
      - ${MYSQL_SUB_DATA}:/var/lib/mysql
    networks:
      database:
        ipv4_address: ${MYSQL_SUB_IP}
  
networks:
  back-end:
    ipam:
      driver: default
      config:
        - subnet: "${BACKEND_SUBNET}"
  front-end:
    ipam:
      driver: default
      config:
        - subnet: "${FRONTEND_SUBNET}"
  database:
    ipam:
      driver: default
      config:
        - subnet: "${DATABASE_SUBNET}"
