version: '3'

services:
  db_main:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_MAIN_PSWD}
    ports: # host:container 
      - ${MYSQL_MAIN_PORT}:3306
    volumes:
      - db-main-vol:/var/lib/mysql
    networks:
      back-end:
        ipv4_address: ${MYSQL_MAIN_IP}

  db_sub:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_SUB_PSWD}
    ports: # host:container
      - ${MYSQL_SUB_PORT}:3306
    volumes:
      - db-sub-vol:/var/lib/mysql
    networks:
      back-end:
        ipv4_address: ${MYSQL_SUB_IP}
  
networks:
  back-end:
    ipam:
      driver: default
      config:
        - subnet: "${BACKEND_SUBNET}"
  front-end:
    ipam:
      driver: default
      config:
        - subnet: "${FRONTEND_SUBNET}"
volumes:
  db-main-vol:
  db-sub-vol:
