version: '3'

services:
  # subsys_admin:
  #   build: 
  #     context: ../backend-admin
  #   depends_on:
  #     - db_main
  #   environment: 
  #     ENV: "development"
  #   ports: 
  #     - 9911:8000
  #   volumes: 
  #     - ../backend-admin/app:/home/admin/app
  #     - ../backend-admin/resources:/home/admin/resources
  #   networks:
  #     all:
  #       ipv4_address: ${BACKEND_ADMIN_IP}

  # subsys_researcher:
  #   build: 
  #     context: ../backend-researcher
  #   environment: 
  #     ENV: "development"
  #   ports: 
  #     - 9912:8000
  #   volumes: 
  #     - ../backend-researcher/app:/home/researcher/app
  #   networks:
  #     all:
  #       ipv4_address: ${BACKEND_RESEARCHER_IP}

  # subsys_tracer:
  #   build: 
  #     context: ../backend-tracer
  #   environment: 
  #     ENV: "development"
  #   ports: 
  #     - 9913:8000
  #   volumes: 
  #     - ../backend-tracer/app:/home/tracer/app
  #   networks:
  #     all:
  #       ipv4_address: ${BACKEND_TRACER_IP}
      
  # vault:
  #   build:
  #     context: ../vault
  #   volumes:
  #     - ${VAULT_CONFIG}:/vault/config
  #     - ${VAULT_POLICIES}:/vault/policies
  #     - ${VAULT_DATA}:/vault/data
  #     - ${VAULT_SCRIPTS}:/home/vault
  #   ports:
  #     - 8200:8200
  #   environment:
  #     - VAULT_ADDR=http://0.0.0.0:8200
  #     - VAULT_API_ADDR=http://0.0.0.0:8200
  #     - VAULT_ADDRESS=http://0.0.0.0:8200
  #   cap_add:
  #     - IPC_LOCK
  #   command: vault server -config=/vault/config/vault.json
  #   networks:
  #     all:
  #       ipv4_address: ${VAULT_IP}

  db_main:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_MAIN_PSWD}
    ports: # host:container 
      - ${MYSQL_MAIN_PORT}:3306
    volumes:
      - ${MYSQL_MAIN_DATA}:/var/lib/mysql
    networks:
      all:
        ipv4_address: ${MYSQL_MAIN_IP}
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=${MYSQL_MAIN_PSWD} 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }

  # db_sub:
  #   image: mysql:8.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_SUB_PSWD}
  #   ports: # host:container
  #     - ${MYSQL_SUB_PORT}:3306
  #   volumes:
  #     - ${MYSQL_SUB_DATA}:/var/lib/mysql
  #   networks:
  #     all:
  #       ipv4_address: ${MYSQL_SUB_IP}

networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 172.16.11.0/27
  

# networks:
#   back-end:
#     ipam:
#       driver: default
#       config:
#         - subnet: "${BACKEND_SUBNET}"
#   front-end:
#     ipam:
#       driver: default
#       config:
#         - subnet: "${FRONTEND_SUBNET}"
#   database:
#     ipam:
#       driver: default
#       config:
#         - subnet: "${DATABASE_SUBNET}"
