version: '3'

services:      
  db_main:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_MAIN_PSWD}
    ports: # host:container 
      - ${MYSQL_MAIN_PORT}:3306
    volumes:
      - ${MYSQL_MAIN_DATA}:/var/lib/mysql
    networks:
      database:
        ipv4_address: ${MYSQL_MAIN_IP}

  db_sub:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_SUB_PSWD}
    ports: # host:container
      - ${MYSQL_SUB_PORT}:3306
    volumes:
      - ${MYSQL_SUB_DATA}:/var/lib/mysql
    networks:
      database:
        ipv4_address: ${MYSQL_SUB_IP}
        
  vault:
    build:
      context: ../vault
    volumes:
      - ${VAULT_CONFIG}:/vault/config
      - ${VAULT_POLICIES}:/vault/policies
      - ${VAULT_DATA}:/vault/data
      - ${VAULT_SCRIPTS}:/home/vault
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
    networks:
      all:
        ipv4_address: ${VAULT_IP}
  
networks:
  database:
    ipam:
      driver: default
      config:
        - subnet: "${DATABASE_SUBNET}"
